version: '3'

services:
    account-service:
        container_name: account-service
        image: account-service:latest
        build: 
            context: .
            dockerfile: ./docker/account.Dockerfile
        ports:
            - 8081:8080
        networks:
            - global-network
            - account-network

    product-service:
        container_name: product-service
        image: product-service:latest
        build: 
            context: .
            dockerfile: ./docker/product.Dockerfile
        ports:
            - 8082:8080
        networks:
            - global-network
            - product-network

    # order-service:
    #     container_name: order-service
    #     image: order-service:latest
    #     build: 
    #         context: ./docker
    #         dockerfile: order.Dockerfile
    #     ports:
    #         - 8083:8080
    #     networks:
    #         - global-network

    mysql-account:
        container_name: mysql-account
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'ecommerce'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - account-network

networks:
    global-network:
        driver: bridge

    account-network:
        driver: bridge
        
    product-network:
        driver: bridge