package constant

const ORDER_STATUS_PENDING = "PENDING"
const ORDER_STATUS_COMPLETED = "COMPLETED"
const ORDER_STATUS_CANCELLED = "CANCELLED"

const PAYMENT_STATUS_AWAITING = "AWAITING PAYMENT"
const PAYMENT_STATUS_COMPLETED = "COMPLETED"
const PAYMENT_STATUS_CANCELLED = "CANCELLED"

const SHIPPING_STATUS_AWAITING = "AWAITING SHIPPING"
const SHIPPING_STATUS_COMPLETED = "COMPLETED"
const SHIPPING_STATUS_CANCELLED = "CANCELLED"
