version: '3'

services:
    account-service:
        container_name: account-service
        image: account-service:latest
        build: 
            context: .
            dockerfile: account.Dockerfile
        ports:
            - 8081:8080
        networks:
            - spring-cloud-network

    product-service:
        container_name: product-service
        image: product-service:latest
        build: 
            context: .
            dockerfile: product.Dockerfile
        ports:
            - 8082:8080
        networks:
            - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge